version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'

#  user-service:
#    image: 'ubuntu:latest'
#    build:
#      context: .
#    volumes:
#      - ./C:\protoc:/workspace
#    working_dir: /workspace
#    command: [ "bash", "-c", "protoc --java_out=./generated --proto_path=./ your-proto-file.proto" ]

