version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=connectattoo'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5432:5432'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  user-service:
    build:
      context: './template'
    ports:
      - '8081:8080'
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"